### ISSUE TITLE
Not able to open ome.tiff image without converting to tif fromat

### ISSUE THREAD

**Issue by kaizen89** [TissUUmaps/TissUUmaps#12]
Hi,
I have `ome.tif` files generated with `qupath` that I can not open with `TissUUmaps`. I can only open them after converting to tif format which increases the size a lot. Is there a way to use an `ome.tif` file directly exported from qupath?

**Comment by cavenel** [comment]
Hi @kaizen89,

TissUUmaps uses OpenSlide to read images, which does not support `OME.tif` yet (there is a pull request https://github.com/openslide/openslide/pull/344). We are also working on a branch that will support more formats natively using tifffile instead of OpenSlide, but it is not finalized yet and there is no ETA on this.
When a format is not recognized, TissUUmaps tries to create a pyramidal tif file using VIPS, so most of `OME.tif` files should be converted automatically and opened in TissUUmaps. I had some cases were even VIPS failed to open them though.

What I usually do is use these options in QuPath:
![image](https://user-images.githubusercontent.com/6164758/208299919-fb0a934c-2528-43e8-8080-d7fb18edad25.png)

And then TissUUmaps manages to convert them to a pyramidal file that is not way bigger.

(I transfered your issue to the main TissUUmaps repo as it is not related to the core js/html)

**Comment by kaizen89** [comment]
Somehow, this did not work for me, only works when exporting as`tif` files.
