### ISSUE TITLE
Problem with TissUUmaps docker images

### ISSUE THREAD

**Issue by Artur-man** [TissUUmaps/TissUUmaps#69]
Hello there, 

I am currently exploring how to deploy TissUUmaps sessions on the web, making it accessible for collaborators. 

Until now saving spatial data as a legacy Spatial AnnData object (h5ad) and opening in a TissUUmaps app was practical but I am wondering if I can use the same h5ad to start a TissUUmaps session in the docker image. 
https://tissuumaps.github.io/installation/

However, the session starts blank even if I put a tif image or an h5ad under `/images/share` as instructed. 

Thanks in advance!

**Comment by cavenel** [comment]
Hi @Artur-man!

In theory it should work with h5ad files on docker as long as they work locally in the app. The instructions are here: https://tissuumaps.github.io/TissUUmaps-docs/docs/sharing/docker.html 

The important things to check are:
- the h5ad should be mounted in docker to `/mnt/data/shared`. Either by mounting directly the folder to `/mnt/data/shared`, or to create a sub folder `shared` and mount it in `/mnt/data` (as the doc says).
- you access the file `my_filename.h5ad` via the url `https://localhost:port/my_filename.h5ad` with correct localhost, port and filename

If you have the two things, it should work correctly using the command:
```bash
docker run -it -p 56733:80 --name=tissuumaps -v /path/to/your/h5ad_files/:/mnt/data/shared cavenel/tissuumaps:latest
```
Then file `/path/to/your/h5ad_files/my_filename.h5ad` will be available on `https://localhost:56733/my_filename.h5ad`

The documentation is not super clear about the /mnt/data/shared folder (and the path is a bit strange...) so that is probably where the issue comes from!

*Side note:*
If you want a default file to be loaded, without specifying its name in the command line, it is also possible by creating a tissuumaps config file and mounting it in docker:
Create a `tissuumaps.cfg` file containing:
```
READ_ONLY = True
PLUGIN_FOLDER = "/mnt/data/plugins/"
SLIDE_DIR = "/mnt/data/shared/"
DEFAULT_PROJECT = "integrated_adata.h5ad"
```
and mount it to `/tissuumaps.cfg` in docker:
```bash
docker run -it -p 56733:80 \
  --name=tissuumaps \
  -v /path/to/your/h5ad_files/:/mnt/data/shared \
  -v /path/to/your/tissuumaps.cfg:/tissuumaps.cfg \
  cavenel/tissuumaps:latest
```
Then you can load `http://localhost:56733` directly.

**Comment by Artur-man** [comment]
The solution worked thanks so much @cavenel!
